"""add game state fields to users

Revision ID: 5b2ffc77b36e
Revises: 0003_add_is_active_to_users
Create Date: 2026-05-09 14:36:46.049578

"""
from alembic import op
import sqlalchemy as sa


revision = '5b2ffc77b36e'
down_revision = '0003_add_is_active_to_users'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('current_infinity_level', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('current_type', sa.String(length=50), server_default='standard', nullable=False))
        batch_op.add_column(sa.Column('highest_type', sa.String(length=50), server_default='standard', nullable=False))
        batch_op.add_column(sa.Column('clicks_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress_percent', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('progress_percent')
        batch_op.drop_column('clicks_remaining')
        batch_op.drop_column('highest_type')
        batch_op.drop_column('current_type')
        batch_op.drop_column('current_infinity_level')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
