"""added game_state table

Revision ID: 9e3602ddd734
Revises: 0003_add_is_active_to_users
Create Date: 2026-05-10 18:49:31.967616

"""
from alembic import op
import sqlalchemy as sa


revision = '9e3602ddd734'
down_revision = '0003_add_is_active_to_users'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('current_infinity_level', sa.Integer(), nullable=False),
    sa.Column('current_type', sa.String(length=50), nullable=False),
    sa.Column('highest_type', sa.String(length=50), nullable=False),
    sa.Column('clicks_remaining', sa.Integer(), nullable=True),
    sa.Column('click_power_lvl', sa.Integer(), nullable=False),
    sa.Column('autoclicker_lvl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_states_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_states_user_id'))

    op.drop_table('game_states')
    # ### end Alembic commands ###
